### ISSUE TITLE
Naming conventions, URN informations fail

### ISSUE THREAD

**Issue by nevenjovanovic** [Capitains/docker-hooktest#1]
@PonteIneptique - following the instructions on http://capitains.github.io/pages/guidelines , I have built a `croala` repository with one simple file (just verse lines). The `Hooktest` reports that URN informations and naming conventions fail the tests. Then I have tried to apply the Hooktest on the `csel-dev-master` repository; there I also see URN informations and naming conventions failing (there the result is `[failed] 332 over 610 texts have fully passed the tests`). In the guidelines I cannot find enough information to make the URN and naming convention pass. What should I do?

Here are the test results for my single-file setup:

<code>
neven@figulus:~/rad/capit/docker-capitains-nemo-nautilus/volumes/repositories$ docker run -i -t --name hooktest -v /home/neven/rad/capit/docker-capitains-nemo-nautilus/volumes/repositories/croala:/sources capitains/hooktest:latest
bash-4.3# ./tei.sh

Starting tests !

Files to test : 3

Testing data/vrancicm532/**cts**.xml

File parsing passed

Parsed

MyCapytain parsing passed

TextGroup detected

Metadata availability passed

1 groupname found

URNs testing passed

Group urn :urn:cts:latinLit:vrancicm532

Testing data/vrancicm532/error532/**cts**.xml

File parsing passed

Parsed

MyCapytain parsing passed

Work detected

Metadata availability passed

1 titles found

1/1 file(s) with labels

1/1 file(s) with descs

URNs testing passed

Group urn : urn:cts:latinLit:vrancicm532

Work urn : urn:cts:latinLit:vrancicm532.error532

Editions and translations urns : urn:cts:latinLit:vrancicm532.error532.croala-lat1

Testing /vrancicm532/error532/vrancicm532.error532.croala-lat1.xml

File parsing passed

Parsed

File ingesting in MyCapytain passed

URN informations failed

Naming conventions failed

RefsDecl parsing passed

1 citation's level found

Passage level parsing passed

178 found

Unique nodes found by XPath passed

Available in inventory failed

TEI DTD Validation passed

End of the test !

[failed] 2 over 3 texts have fully passed the tests

</code>

**Comment by PonteIneptique** [comment]
Hi @nevenjovanovic,
I think you just found an issue with the tester / the guidelines. Both issue comes from finding the URN in the objects. We never worked with plain TEI (but rather Epidoc) hence having more chance to discover issue there. The way to fix this issue (for the time being) would be to put your `n="urn:cts:latinLit..."` attribute in the //tei:text node instead of the body. Is it ok for you ?

PS : You know you are actually doing the content of the workshop the week before ? :O

**Comment by nevenjovanovic** [comment]
Excellent!
<code>

> End of the test !
> 
> [success] 3 over 3 texts have fully passed the tests
> </code>
