### ISSUE TITLE
CTS for sibling levels?

### ISSUE THREAD

**Issue by nevenjovanovic** [Capitains/docker-hooktest#2]
My file is a TEI XML edition of a letter. It has the following structure:
<code>
div

> opener
> 
> p
> 
> closer

div
</code>

Now, I want to use CTS to refer to the three sibling levels `opener, p, closer`. This seems not to be possible in the CapiTainS suite, as the Hooktest seems to expect nested structure -- the second XPath should describe the parent of the first, etc, while my XPath look like this:

``` xml
<refsDecl n="CTS">
       <cRefPattern n="incipit"
         matchPattern="(\w+)"
         replacementPattern="#xpath(/tei:TEI/tei:text/tei:body/tei:div/tei:opener[@n='$1'])">
          <p>This pattern references opener of the text in CTS.</p>
       </cRefPattern>
       <cRefPattern n="paragraphus"
         matchPattern="(\w+)"
         replacementPattern="#xpath(/tei:TEI/tei:text/tei:body/tei:div/tei:p[@n='$1'])">
          <p>This pattern references p of the text in CTS.</p>
       </cRefPattern>
       <cRefPattern n="explicit"
         matchPattern="(\w+)"
         replacementPattern="#xpath(/tei:TEI/tei:text/tei:body/tei:div/tei:closer[@n='$1'])">
          <p>This pattern references closer of the text in CTS.</p>
       </cRefPattern>
     </refsDecl>
```

I will experiment to see whether a regex would be acceptable as the last element (that is: `#xpath(/tei:TEI/tei:text/tei:body/tei:div/tei:*[@n='$1']`).

**Comment by PonteIneptique** [comment]
What we often use is the following xpath 1 syntax : 
`/*[self::tei:div or self::tei:l][@n='$1'])`

**Comment by nevenjovanovic** [comment]
Ah, it passes! Now to see what the Capitains Docker will say...
